-- MySQL Script generated by MySQL Workbench
-- 01/10/16 23:45:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema erp_depil_soft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp_depil_soft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'erp_depil_soft' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE 'erp_depil_soft' ;

-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'categorias_de_produtos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'categorias_de_produtos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'categorias_de_produtos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'produtos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'produtos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'produtos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_categoria' INT NULL,
  'nome' VARCHAR(45) NULL,
  'descricao' LONGTEXT NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  'tipo' ENUM('PRODUTO', 'SERVICO') NULL,
  'valor_custo' VARCHAR(45) NULL,
  'valor_bruto' VARCHAR(45) NULL,
  'lucro' VARCHAR(45) NULL,
  'quant_min' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_categoria_idx' ('fk_categoria' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'grupos_de_clientes'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'grupos_de_clientes' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'grupos_de_clientes' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'clientes'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'clientes' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'clientes' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_grupo' INT NULL,
  'nome' VARCHAR(250) NULL,
  'sexo' ENUM('MASC', 'FEM') NULL,
  'logradouro' VARCHAR(250) NULL,
  'num' VARCHAR(20) NULL,
  'bairro' VARCHAR(250) NULL,
  'cidade' VARCHAR(250) NULL,
  'uf' VARCHAR(5) NULL,
  'pais' VARCHAR(45) NULL,
  'cep' VARCHAR(45) NULL,
  'nascimento' DATE NULL,
  'cpf' VARCHAR(45) NULL,
  'tel_1' VARCHAR(45) NULL,
  'tel_2' VARCHAR(45) NULL,
  'email' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_grupo_idx' ('fk_grupo' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'cargos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'cargos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'cargos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'colaboradores'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'colaboradores' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'colaboradores' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'nome' VARCHAR(250) NULL,
  'cpf' VARCHAR(45) NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  'tel_interno' VARCHAR(45) NULL,
  'tel_pessoal' VARCHAR(45) NULL,
  'email' VARCHAR(250) NULL,
  'valor_comissao' VARCHAR(45) NULL,
  'tipo_comissao' ENUM('PORCENTAGEM') NULL,
  'fk_cargo' INT NULL,
  'fk_usuario' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_cargo_idx' ('fk_cargo' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'convenios'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'convenios' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'convenios' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'valor_desconto' VARCHAR(45) NULL,
  'tipo_desconto' ENUM('VALOR','PORCENTAGEM', 'CORTESIA') NULL,
  'data_inicio' DATE NULL,
  'data_fim' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'cabines'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'cabines' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'cabines' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'tipos_de_pagamento'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'tipos_de_pagamento' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'tipos_de_pagamento' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  'tipo' ENUM('DINHEIRO', 'CREDITO', 'DEBITO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'caixas'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'caixas' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'caixas' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'nome' VARCHAR(45) NULL,
  'data_abertura' DATE NULL,
  'hora_abertura' INT NULL,
  'min_abertura' INT NULL,
  'data_fechamento' DATE NULL,
  'hora_fechamento' INT NULL,
  'min_fechamento' INT NULL,
  'fk_user_abertura' INT NULL,
  'fk_user_fechamento' INT NULL,
  'valor_inicial' VARCHAR(45) NULL,
  'status' ENUM('ABERTO', 'FECHADO') NULL,
  'valor_fechamento' VARCHAR(45) NULL,
  'cod_terminal' VARCHAR(250) NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'movimentos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'movimentos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'movimentos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_cliente' INT NULL,
  'fk_colaborador_encaminhar' INT NULL,
  'fk_usuario_resp' INT NULL,
  'fk_convenio' INT NULL,
  'fk_cabine' INT NULL,
  'fk_caixa' INT NULL,
  'fk_tipo_pagamento' INT NULL,
  'data_abertura' DATE NULL,
  'hora_abertura' INT NULL,
  'min_abertura' INT NULL,
  'data_fechamento' DATE NULL,
  'hora_fechamento' INT NULL,
  'min_fechamento' INT NULL,
  'valor_final' VARCHAR(45) NOT NULL,
  'desconto' VARCHAR(45) NULL,
  'status_pagamento' ENUM('ABERTO','FECHADO', 'CANCELADO') NULL,
  'valor_bruto' VARCHAR(45) NULL,
  'motivo_cancelamento' VARCHAR(250) NULL,
  'desconto_convenio' VARCHAR(45) NULL,
  'status_atendimento' ENUM('NAO ENCAMINHADO', 'ENCAMINHADO', 'EM ATENDIMENTO', 'FINALIZADO') NULL,
  'valor_comissao' VARCHAR(45) NULL,
  'sinc_server' ENUM('SIM', 'NAO') NULL,
  'adicional_hora_marcada' VARCHAR(45) NULL,
  'obs' LONGTEXT NULL,
  PRIMARY KEY ('id', 'valor_final'),
  INDEX 'fk_cliente_idx' ('fk_cliente' ASC),
  INDEX 'fk_colaborador_idx' ('fk_colaborador_encaminhar' ASC),
  INDEX 'fk_convenio_idx' ('fk_convenio' ASC),
  INDEX 'fk_cabine_idx' ('fk_cabine' ASC),
  INDEX 'fk_tipo_pagamento_idx' ('fk_tipo_pagamento' ASC),
  INDEX 'fk_caixa_idx' ('fk_caixa' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'unidade'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'unidade' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'unidade' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'codigo' VARCHAR(250) NOT NULL,
  'nome' VARCHAR(250) NULL,
  'subtitulo' VARCHAR(250) NULL,
  'nome_completo' VARCHAR(250) NULL,
  'endereco' VARCHAR(250) NULL,
  'tel_1' VARCHAR(45) NULL,
  'tel_2' VARCHAR(45) NULL,
  'site' VARCHAR(250) NULL,
  'email' VARCHAR(250) NULL,
  'pais_padrao' VARCHAR(250) NULL,
  'cidade_padrao' VARCHAR(250) NULL,
  'itens_por_pagina' INT NULL,
  'saldo_inicial_caixa' VARCHAR(45) NULL,
  'desconto_padrao' VARCHAR(45) NULL,
  'porcento_lucro_produto' VARCHAR(45) NULL,
  'porcento_lucro_servico' VARCHAR(45) NULL,
  'quant_min_estoque' INT NULL,
  'quant_min_inventario' INT NULL,
  'porcento_multa_padrao' VARCHAR(45) NULL,
  'porcento_juros_ao_mes_padrao' VARCHAR(45) NULL,
  'num_dias_mes_comercial' INT NULL,
  'porcento_comissao_padrao' VARCHAR(45) NULL,
  'taxa_hora_marcada' VARCHAR(45) NULL,
  'nome_identificador' VARCHAR(250) NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'grupos_de_fornecedores'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'grupos_de_fornecedores' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'grupos_de_fornecedores' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'fornecedores'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'fornecedores' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'fornecedores' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_grupo' INT NULL,
  'nome_razao' VARCHAR(250) NULL,
  'tipo' ENUM('PF','PJ') NULL,
  'cpf_cnpj' VARCHAR(45) NULL,
  'nome_fantasia_apelido' VARCHAR(250) NULL,
  'tel_1' VARCHAR(45) NULL,
  'tel_2' VARCHAR(45) NULL,
  'fax' VARCHAR(45) NULL,
  'banco' VARCHAR(250) NULL,
  'agencia' VARCHAR(45) NULL,
  'conta' VARCHAR(45) NULL,
  'email' VARCHAR(250) NULL,
  'nome_responsavel' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_grupo_idx' ('fk_grupo' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'estoque'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'estoque' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'estoque' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_produto' INT NULL,
  'quantidade' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_produto_idx' ('fk_produto' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'grupos_de_itens_de_inventario'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'grupos_de_itens_de_inventario' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'grupos_de_itens_de_inventario' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'item_de_inventario'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'item_de_inventario' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'item_de_inventario' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'nome' VARCHAR(45) NULL,
  'descricao' LONGTEXT NULL,
  'data_cadastro' DATE NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  'valor_medio' VARCHAR(45) NULL,
  'fk_grupo' INT NULL,
  'tipo' ENUM('NORMAL', 'FRACIONADO') NULL,
  'quant_fracionada' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_grupo_idx' ('fk_grupo' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'inventario'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'inventario' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'inventario' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_item' INT NULL,
  'quant' INT NULL,
  'quant_fracionada' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_item_idx' ('fk_item' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'credores'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'credores' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'credores' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'nome_razao' VARCHAR(250) NULL,
  'cpf_cnpj' VARCHAR(45) NULL,
  'tel_1' VARCHAR(45) NULL,
  'tel_2' VARCHAR(45) NULL,
  'email' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  'tipo' ENUM('PF', 'PJ') NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'pagamentos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'pagamentos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'pagamentos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'referente' VARCHAR(250) NULL,
  'fk_fornecedor' INT NULL,
  'fk_credor' INT NULL,
  'tipo' ENUM('UNICO', 'PARCELADO') NULL,
  'valor_entrada' VARCHAR(45) NULL,
  'valor_total' VARCHAR(45) NULL,
  'data_cadastro' DATE NULL,
  'num_de_parcelas' INT NULL,
  'porcento_multa' VARCHAR(45) NULL,
  'porcento_juros' VARCHAR(45) NULL,
  'status' ENUM('ABERTO', 'EM PAGAMENTO',  'FECHADO') NULL,
  'data_primeiro_vencimento' DATE NULL,
  'sinc_server' ENUM('SIM', 'NAO') NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_fornecedor_idx' ('fk_fornecedor' ASC),
  INDEX 'fk_credores_idx' ('fk_credor' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'despesas'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'despesas' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'despesas' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'compras'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'compras' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'compras' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_inventario' INT NULL,
  'fk_estoque' INT NULL,
  'fk_pagamento' INT NULL,
  'fk_fornecedor' INT NULL,
  'fk_credor' INT NULL,
  'descricao' VARCHAR(250) NULL,
  'quant_total' INT NULL,
  'data_cadastro' DATE NULL,
  'valor_total' VARCHAR(45) NULL,
  'status' ENUM('PENDENTE', 'FECHADO') NULL,
  'data_compra' DATE NULL,
  'tipo' ENUM('INVENTARIO', 'ESTOQUE', 'DESPESAS') NULL,
  'fk_despesa' INT NULL,
  'quant_pacotes' INT NULL,
  'quant_unidades' INT NULL,
  'valor_item_unidade' VARCHAR(45) NULL,
  'valor_item_pacote' VARCHAR(45) NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_inventario_idx' ('fk_inventario' ASC),
  INDEX 'fk_pagamento_idx' ('fk_pagamento' ASC),
  INDEX 'fk_estoque_idx' ('fk_estoque' ASC),
  INDEX 'fk_fornecedor_idx' ('fk_fornecedor' ASC),
  INDEX 'fk_credor_idx' ('fk_credor' ASC),
  INDEX 'fk_despesa_idx' ('fk_despesa' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'movimento_x_produto'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'movimento_x_produto' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'movimento_x_produto' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_movimento' INT NULL,
  'fk_produto' INT NULL,
  'quantidade' INT NULL,
  'valor' VARCHAR(45) NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_movimento_idx' ('fk_movimento' ASC),
  INDEX 'fk_produto_idx' ('fk_produto' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'historico_de_precos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'historico_de_precos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'historico_de_precos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_produto' INT NULL,
  'valor_bruto' VARCHAR(45) NULL,
  'data_cadastro' DATE NULL,
  'fk_usuario' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_produto_idx' ('fk_produto' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'recebimentos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'recebimentos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'recebimentos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'referente' VARCHAR(250) NULL,
  'fk_cliente' INT NULL,
  'fk_vendedor' INT NULL,
  'tipo' ENUM('UNICO', 'PARCELADO') NULL,
  'nome_devedor' VARCHAR(250) NULL,
  'cpf_cnpj_devedor' VARCHAR(45) NULL,
  'dia_vencimento' INT NULL,
  'primeiro_mes' INT NULL,
  'primeiro_ano' INT NULL,
  'valor_entrada' VARCHAR(45) NULL,
  'valor_total' VARCHAR(45) NULL,
  'porcento_comissao' VARCHAR(45) NULL,
  'data_cadastro' DATE NULL,
  'num_de_parcelas' INT NULL,
  'porcento_multa' VARCHAR(45) NULL,
  'porcento_juros' VARCHAR(45) NULL,
  'status' ENUM('ABERTO', 'EM PAGAMENTO',  'FECHADO') NULL,
  'sinc_server' ENUM('SIM', 'NAO') NULL,
  'data_fechamento' DATE NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_cliente_idx' ('fk_cliente' ASC),
  INDEX 'fk_vendedor_idx' ('fk_vendedor' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'parcelas'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'parcelas' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'parcelas' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_a_receber' INT NULL,
  'valor_parcela' VARCHAR(45) NULL,
  'status' ENUM('ABERTO', 'FECHADO') NULL,
  'valor_final' VARCHAR(45) NULL,
  'data_vencimento' DATE NULL,
  'indice' INT NULL,
  'data_pagamento' DATE NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_a_receber_idx' ('fk_a_receber' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'parcelas_pagamentos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'parcelas_pagamentos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'parcelas_pagamentos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_pagamento' INT NULL,
  'valor_parcela' VARCHAR(45) NULL,
  'status' ENUM('ABERTO', 'FECHADO') NULL,
  'valor_final' VARCHAR(45) NULL,
  'data_pagamento' DATE NULL,
  'indice' INT NULL,
  'data_vencimento' DATE NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_pagamento_idx' ('fk_pagamento' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'retiradas'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'retiradas' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'retiradas' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_usuario' INT NULL,
  'fk_colaborador_destino' INT NULL,
  'fk_inventario' INT NULL,
  'data' DATE NULL,
  'hora' INT NULL,
  'min' INT NULL,
  'quant' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_colaborador_destino_idx' ('fk_colaborador_destino' ASC),
  INDEX 'fk_inventario_idx' ('fk_inventario' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'item_x_fornecedor'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'item_x_fornecedor' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'item_x_fornecedor' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_fornecedor' INT NULL,
  'fk_item' INT NULL,
  'valor' VARCHAR(45) NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_fornecedor_idx' ('fk_fornecedor' ASC),
  INDEX 'fk_item_idx' ('fk_item' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'fornecedor_x_produto'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'fornecedor_x_produto' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'fornecedor_x_produto' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_fornecedor' INT NULL,
  'fk_produto' INT NULL,
  'valor' VARCHAR(45) NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_fornecedor_idx' ('fk_fornecedor' ASC),
  INDEX 'fk_produto_idx' ('fk_produto' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'cabines_x_colaboradores'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'cabines_x_colaboradores' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'cabines_x_colaboradores' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_cabine' INT NULL,
  'fk_colaborador' INT NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  'liberado' ENUM('SIM', 'NAO') NULL,
  'horario_liberado_em_mim' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_cabine_idx' ('fk_cabine' ASC),
  INDEX 'fk_colaborador_idx' ('fk_colaborador' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'outras_unidades'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'outras_unidades' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'outras_unidades' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'nome' VARCHAR(250) NULL,
  'descricao' VARCHAR(250) NULL,
  'status' ENUM('ATIVO', 'INATIVO') NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'repasse'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'repasse' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'repasse' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_item' INT NULL,
  'fk_user_resp' INT NULL,
  'quant' INT NULL,
  'data_cadastro' DATE NULL,
  'fk_unidade' INT NULL,
  'tipo' ENUM('ENVIO', 'RECEBIMENTO') NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_item_idx' ('fk_item' ASC),
  INDEX 'fk_unidade_idx' ('fk_unidade' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'movimentos_x_formas_pagamento'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'movimentos_x_formas_pagamento' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'movimentos_x_formas_pagamento' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_movimento' INT NULL,
  'fk_forma_pagamento' INT NULL,
  'valor' VARCHAR(45) NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_forma_pagamento_idx' ('fk_forma_pagamento' ASC),
  INDEX 'fk_movimento_idx' ('fk_movimento' ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'hora_marcada'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'hora_marcada' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'hora_marcada' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'fk_cliente' INT NULL,
  'data' DATE NULL,
  'hora' INT NULL,
  'mim' INT NULL,
  'valor' VARCHAR(45) NULL,
  'status' ENUM('ATENDIDO', 'AGUARDANDO', 'CANCELADO') NULL,
  'fk_depiladora' INT NULL,
  PRIMARY KEY ('id'),
  INDEX 'fk_cliente_idx' ('fk_cliente' ASC),
  INDEX 'fk_depiladora_idx' ('fk_depiladora' ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
