-- MySQL Script generated by MySQL Workbench
-- 01/10/16 23:45:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema erp_depil_soft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema erp_depil_soft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'erp_depil_soft' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE 'erp_depil_soft' ;

-- -----------------------------------------------------
-- Table 'erp_depil_soft'.'categorias_de_produtos'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'erp_depil_soft'.'categorias_de_produtos' ;

CREATE TABLE IF NOT EXISTS 'erp_depil_soft'.'categorias_de_produtos' (
  'id' INT NOT NULL AUTO_INCREMENT,
  'descricao' VARCHAR(250) NULL,
  'data_cadastro' DATE NULL,
  PRIMARY KEY ('id'))
ENGINE = MyISAM;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
